### ISSUE TITLE
Let xarray_extras work with an open file

### ISSUE THREAD

**Issue by deltamarnix** [crusaderky/xarray_extras#37]
I am trying to write a 1D DataArray into a whitespace separated text file. The text file will contain multiple 1D DataArrays with custom headers. I am trying to find the most optimal way to do this and it seems that `xarray_extras` could be twice as fast as my `to_pandas()` implementation.

Problem with `xarray_extras` is that it only allows me to set a path. A workaround for me would be to use `mode="a"`, but I was wondering if it would also be possible to have the file open and give the file handle to xarray-extras.

```py
def create_and_write_extras(data: xr.DataArray):
    with open("myfile.csv", "w") as f:
        promise = xarray_extras.csv.to_csv(
            data,
            f,
            header=False,
            index=False,
            float_format="%.4f",
            lineterminator=" ",
            compression=None,
        )
        promise.compute()
# This would print something like "1.0000 22.0000 45.0000" etc...
```

**Comment by crusaderky** [comment]
File objects are finicky, because they can't be pickled (so they definitely don't work on a distributed dask cluster, and I wouldn't expect them to work on a LocalCluster smoothly, either). Also, file objects without a file descriptor like `io.StringIO` won't work because `to_csv` is implemented in C.

The pattern elsewhere in dask-capable libraries is to allow for an optional `mode="a"` as you correctly pointed out. The overhed of closing and reopening the file handle should be negligible unless you're running on a high-latency network mount.

Would you be willing to write a PR to implement the optional `mode` parameter?

**Comment by deltamarnix** [comment]
Thanks for your quick response. If I am correct, it seems that `mode="a"` is already implemented.

https://github.com/crusaderky/xarray_extras/blob/44e88a78a13ccbb0eda77b7379b8f5c701c4e566/xarray_extras/csv.py#L105-L107

```py
    mode = kwargs.pop("mode", "w")
    if mode not in "wa":
        raise ValueError('mode: expected w or a; got "%s"' % mode)
```

**Comment by crusaderky** [comment]
You are correct.
I'll close this ticket; please reopen if you gather evidence that the close/reopen pattern provokes substantial overhead.
